package com.pratik.learning.familyTree.utils


import com.pratik.learning.familyTree.data.local.dto.FamilyMember
import com.pratik.learning.familyTree.data.local.dto.FamilyRelation
import org.json.JSONObject

// NOTE: You will need to add the following dependency to your build.gradle.kts (app module):
// implementation("org.json:json:20231013")
// or implement a safer, modern parser using kotlinx.serialization or Gson/Jackson.

/**
 * !!! IMPORTANT !!!
 * * REPLACE THIS STRING with the ENTIRE, UNMODIFIED content of your recordBackup.txt file.
 * The content is expected to be split by tabs and contain JSON arrays for members and relations.
 */
const val BACKUP_DATA_STRING = """
{
"familyTree_members" : [
    {
        "id": 1,
        "fullName": "Narbatlal Singh Vishwakarma",
        "gender": "M",
        "dob": "1950-01-01",
        "isLiving": false,
        "dod": "2025-09-26",
        "city": "Dewas",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 2,
        "fullName": "Narabda Vishwakarma",
        "gender": "F",
        "dob": "1960-01-01",
        "isLiving": false,
        "dod": "2023-01-11",
        "city": "Dewas",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 3,
        "fullName": "Kailash Vishwakarma",
        "gender": "M",
        "dob": "1970-03-01",
        "isLiving": true,
        "dod": null,
        "city": "Dewas",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 4,
        "fullName": "Rajni Vishwakarma",
        "gender": "F",
        "dob": "1975-04-28",
        "isLiving": true,
        "dod": null,
        "city": "Dewas",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 5,
        "fullName": "Pratik Vishwakarma",
        "gender": "M",
        "dob": "1994-10-26",
        "isLiving": true,
        "dod": null,
        "city": "Dewas",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 6,
        "fullName": "Shivani Vishwakarma",
        "gender": "F",
        "dob": "1997-05-04",
        "isLiving": true,
        "dod": null,
        "city": "Dewas",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 7,
        "fullName": "Jagannath Ji Vishwakarma",
        "gender": "M",
        "dob": "1925-01-01",
        "isLiving": true,
        "dod": null,
        "city": "Talod",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 8,
        "fullName": "Payal Vishwakarma",
        "gender": "F",
        "dob": "1996-12-10",
        "isLiving": true,
        "dod": null,
        "city": "Sehor",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 9,
        "fullName": "Shritika Vishwakarma",
        "gender": "F",
        "dob": "2024-09-10",
        "isLiving": true,
        "dod": null,
        "city": "Dewas",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 10,
        "fullName": "Kanta Carpenter",
        "gender": "F",
        "dob": "1965-01-01",
        "isLiving": true,
        "dod": null,
        "city": "Dewas",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 11,
        "fullName": "Radheshyam Carpenter",
        "gender": "M",
        "dob": "1960-01-01",
        "isLiving": true,
        "dod": null,
        "city": "Dewas",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 12,
        "fullName": "Abhishek Carpenter",
        "gender": "M",
        "dob": "1992-03-28",
        "isLiving": true,
        "dod": null,
        "city": "Dewas",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 13,
        "fullName": "Kanehya Lal Carpenter",
        "gender": "M",
        "dob": "1950-01-01",
        "isLiving": true,
        "dod": null,
        "city": "Devghar",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 14,
        "fullName": "Sunder Bai Carpenter",
        "gender": "F",
        "dob": "1955-01-01",
        "isLiving": true,
        "dod": null,
        "city": "Devghar",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 15,
        "fullName": "Darshit Carpenter",
        "gender": "M",
        "dob": "2018-05-10",
        "isLiving": true,
        "dod": null,
        "city": "Dewas",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 16,
        "fullName": "Bhavya Carpenter",
        "gender": "M",
        "dob": "2023-01-21",
        "isLiving": true,
        "dod": null,
        "city": "Dewas",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 17,
        "fullName": "Rameshchandra Vishwakarma",
        "gender": "M",
        "dob": "1966-12-03",
        "isLiving": true,
        "dod": null,
        "city": "Dewas",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 18,
        "fullName": "Kanta Vishwakarma",
        "gender": "F",
        "dob": "1970-11-01",
        "isLiving": true,
        "dod": null,
        "city": "Dewas",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 19,
        "fullName": "Satish Vishwakarma",
        "gender": "M",
        "dob": "1988-11-09",
        "isLiving": true,
        "dod": null,
        "city": "Dewas",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 20,
        "fullName": "Akshat Vishwakarma",
        "gender": "M",
        "dob": "2009-02-10",
        "isLiving": true,
        "dod": null,
        "city": "Dewas",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 21,
        "fullName": "Jaya Vishwakarma",
        "gender": "F",
        "dob": "1992-12-29",
        "isLiving": true,
        "dod": null,
        "city": "Dewas",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 22,
        "fullName": "Pooja Carpenter",
        "gender": "F",
        "dob": "1992-11-14",
        "isLiving": true,
        "dod": null,
        "city": "Dewas",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 23,
        "fullName": "Reshambai Vishwakarma",
        "gender": "F",
        "dob": "1920-01-01",
        "isLiving": false,
        "dod": "1960-01-01",
        "city": "Talod",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 24,
        "fullName": "PoonaJi Vishwakarma",
        "gender": "M",
        "dob": "1900-01-01",
        "isLiving": false,
        "dod": "1950-01-01",
        "city": "Talod",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 25,
        "fullName": "Metabbai Vishwakarma",
        "gender": "F",
        "dob": "1900-01-01",
        "isLiving": false,
        "dod": "1950-01-01",
        "city": "Talod",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 26,
        "fullName": "Balaji Vishwakarma",
        "gender": "M",
        "dob": "1900-01-01",
        "isLiving": false,
        "dod": "1950-01-01",
        "city": "Talod",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 27,
        "fullName": "Motilal Vishwakarma",
        "gender": "M",
        "dob": "1900-01-01",
        "isLiving": false,
        "dod": "1950-01-01",
        "city": "Talod",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 28,
        "fullName": "Shetanbai vishwakarma",
        "gender": "F",
        "dob": "1900-01-01",
        "isLiving": false,
        "dod": "1950-01-01",
        "city": "talod",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 29,
        "fullName": "Ramchandra Ji Vishwakarma",
        "gender": "M",
        "dob": "1900-01-01",
        "isLiving": false,
        "dod": "1900-01-01",
        "city": "Talod",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 30,
        "fullName": "Chuunilal Ji Vishwakarma",
        "gender": "M",
        "dob": "1900-01-01",
        "isLiving": false,
        "dod": "1900-01-01",
        "city": "Talod",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 31,
        "fullName": "Misarbai Vishwakarma",
        "gender": "F",
        "dob": "1900-01-01",
        "isLiving": false,
        "dod": "1900-01-01",
        "city": "Talod",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 32,
        "fullName": "Bhagirath Ji Vishwakarma",
        "gender": "M",
        "dob": "1900-01-01",
        "isLiving": false,
        "dod": "1900-01-01",
        "city": "Talod",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 33,
        "fullName": "Anandi Bai Vishwakarma",
        "gender": "F",
        "dob": "1900-01-01",
        "isLiving": false,
        "dod": "1900-01-01",
        "city": "Talod",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 34,
        "fullName": "Ajodhiya Bai Vishwakarma",
        "gender": "F",
        "dob": "1900-01-01",
        "isLiving": false,
        "dod": "1900-01-01",
        "city": "Talod",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 35,
        "fullName": "Babu Lal Vishwakarma",
        "gender": "M",
        "dob": "1955-01-01",
        "isLiving": true,
        "dod": null,
        "city": "Talod",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 36,
        "fullName": "Bhagwanta Bai Vishwakarma",
        "gender": "F",
        "dob": "1956-01-01",
        "isLiving": true,
        "dod": null,
        "city": "Talod",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 37,
        "fullName": "Shivnaranay Vishwakarma",
        "gender": "M",
        "dob": "1972-01-01",
        "isLiving": true,
        "dod": null,
        "city": "Talod",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 38,
        "fullName": "Madhu Vishwakarma",
        "gender": "F",
        "dob": "1978-01-01",
        "isLiving": false,
        "dod": "2008-01-01",
        "city": "Talod",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 39,
        "fullName": "Deepak Vishwakarma",
        "gender": "M",
        "dob": "1994-01-01",
        "isLiving": true,
        "dod": null,
        "city": "Dewas",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 40,
        "fullName": "Rahul Vishwakarma",
        "gender": "M",
        "dob": "1996-01-01",
        "isLiving": true,
        "dod": null,
        "city": "Dewas",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 41,
        "fullName": "Seshpal Vishwakarma",
        "gender": "M",
        "dob": "1980-01-01",
        "isLiving": true,
        "dod": null,
        "city": "Talod",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 42,
        "fullName": "Lakshmi Vishwakarma",
        "gender": "F",
        "dob": "1985-01-01",
        "isLiving": true,
        "dod": null,
        "city": "Talod",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 43,
        "fullName": "Ankit Vishwakarma",
        "gender": "M",
        "dob": "2005-01-01",
        "isLiving": true,
        "dod": null,
        "city": "Dewas",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 44,
        "fullName": "Soniya Vishwakarma",
        "gender": "F",
        "dob": "2000-01-01",
        "isLiving": true,
        "dod": null,
        "city": "Dewas",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 45,
        "fullName": "Geetabai Vishwakarma",
        "gender": "F",
        "dob": "1900-01-01",
        "isLiving": false,
        "dod": "1900-01-01",
        "city": "Kachiguradiya",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 46,
        "fullName": "Lakshmi Narayan Vishwakarma",
        "gender": "M",
        "dob": "1900-10-01",
        "isLiving": false,
        "dod": "1900-01-01",
        "city": "Kachigurardiya",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 47,
        "fullName": "Radheshyam Vishwakarma",
        "gender": "M",
        "dob": "1900-01-01",
        "isLiving": true,
        "dod": null,
        "city": "Kachigurardiya",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 48,
        "fullName": "Manoharlal Vishwakarma",
        "gender": "M",
        "dob": "1956-01-01",
        "isLiving": false,
        "dod": "2020-01-01",
        "city": "Sonkatch",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 49,
        "fullName": "Avanti Bai Vishwakarma",
        "gender": "F",
        "dob": "1900-01-01",
        "isLiving": true,
        "dod": null,
        "city": "Sonkatch",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 50,
        "fullName": "Sunil Vishwakarma",
        "gender": "M",
        "dob": "1980-01-01",
        "isLiving": true,
        "dod": null,
        "city": "Sonkatch",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 51,
        "fullName": "Laddu Vishwakarma",
        "gender": "M",
        "dob": "2010-01-01",
        "isLiving": true,
        "dod": null,
        "city": "Sonkatch",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 52,
        "fullName": "Om Vishwakarma",
        "gender": "M",
        "dob": "1985-01-01",
        "isLiving": true,
        "dod": null,
        "city": "Sonkatch",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 53,
        "fullName": "Rajesh Vishwakarma",
        "gender": "M",
        "dob": "1990-01-01",
        "isLiving": true,
        "dod": null,
        "city": "Sonkatch",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 54,
        "fullName": "Baal Krishna Vishwakarma",
        "gender": "M",
        "dob": "1960-01-01",
        "isLiving": true,
        "dod": null,
        "city": "Talod",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 55,
        "fullName": "Seeta Bai Vishwakarma",
        "gender": "F",
        "dob": "1968-01-01",
        "isLiving": true,
        "dod": null,
        "city": "Talod",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 57,
        "fullName": "Ravi Vishwakarma",
        "gender": "M",
        "dob": "1970-01-01",
        "isLiving": true,
        "dod": null,
        "city": "Talod",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 58,
        "fullName": "Ghasiram Ji Vishwakarma",
        "gender": "M",
        "dob": "1900-01-01",
        "isLiving": false,
        "dod": "1900-01-01",
        "city": "Talod",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 59,
        "fullName": "Ganga Bai Vishwakarma",
        "gender": "F",
        "dob": "1900-01-01",
        "isLiving": false,
        "dod": "1900-01-01",
        "city": "Talod",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 60,
        "fullName": "Sundar Bai Vishwakarma",
        "gender": "F",
        "dob": "1900-01-01",
        "isLiving": false,
        "dod": "1900-01-01",
        "city": "Salamkhadi",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 61,
        "fullName": "Kaaluram Ji Vishwakarma",
        "gender": "M",
        "dob": "1900-01-01",
        "isLiving": false,
        "dod": "1900-01-01",
        "city": "Salamkhadi",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 62,
        "fullName": "Rajaram ji Vishwakarma",
        "gender": "M",
        "dob": "1900-01-01",
        "isLiving": false,
        "dod": "2010-01-01",
        "city": "Talod",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 63,
        "fullName": "Dinesh Vishwakarma",
        "gender": "M",
        "dob": "1980-01-01",
        "isLiving": true,
        "dod": null,
        "city": "Talod",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 64,
        "fullName": "Mukesh Vishwakarma",
        "gender": "M",
        "dob": "1975-01-01",
        "isLiving": true,
        "dod": null,
        "city": "Talod",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 65,
        "fullName": "Harshit Vishwakarma",
        "gender": "M",
        "dob": "2000-01-01",
        "isLiving": true,
        "dod": null,
        "city": "Talod",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 66,
        "fullName": "Teena",
        "gender": "F",
        "dob": "1998-01-01",
        "isLiving": true,
        "dod": null,
        "city": "Talod",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 67,
        "fullName": "Vishnu Vishwakarma",
        "gender": "F",
        "dob": "1965-01-01",
        "isLiving": true,
        "dod": null,
        "city": "Talod",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 68,
        "fullName": "Babita Vishwakarma",
        "gender": "F",
        "dob": "1968-01-01",
        "isLiving": true,
        "dod": null,
        "city": "Talod",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 69,
        "fullName": "Mahendra Vishwakarma",
        "gender": "M",
        "dob": "2004-01-01",
        "isLiving": true,
        "dod": null,
        "city": "Talod",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 70,
        "fullName": "Aman Vishwakarma",
        "gender": "M",
        "dob": "2007-01-01",
        "isLiving": true,
        "dod": null,
        "city": "Talod",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 71,
        "fullName": "Radha Bai Vishwakarma",
        "gender": "F",
        "dob": "1960-01-01",
        "isLiving": true,
        "dod": null,
        "city": "Talod",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 72,
        "fullName": "Usha Vishwakarma",
        "gender": "F",
        "dob": "1970-01-01",
        "isLiving": true,
        "dod": null,
        "city": "Panigaav",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 73,
        "fullName": "Mahesh Vishwakarma",
        "gender": "M",
        "dob": "1970-01-01",
        "isLiving": true,
        "dod": null,
        "city": "Panigaav",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 74,
        "fullName": "Ramu Bai Vishwakarma",
        "gender": "F",
        "dob": "1900-01-01",
        "isLiving": true,
        "dod": null,
        "city": "Jamgod",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 75,
        "fullName": "Nathuram Ji Vishwakarma",
        "gender": "M",
        "dob": "1900-01-01",
        "isLiving": false,
        "dod": "1900-01-01",
        "city": "Jamgod",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 76,
        "fullName": "Raam Narayan Vishwakarma",
        "gender": "M",
        "dob": "1935-01-01",
        "isLiving": true,
        "dod": null,
        "city": "Jamgod",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 77,
        "fullName": "Babu Lal Ji Vishwakarma",
        "gender": "M",
        "dob": "1945-01-01",
        "isLiving": false,
        "dod": "1945-01-01",
        "city": "Jamgod",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 78,
        "fullName": "Shritik Vishwakarma",
        "gender": "M",
        "dob": "2024-09-10",
        "isLiving": true,
        "dod": null,
        "city": "Dewas",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 79,
        "fullName": "Rameshwar Vishwakarma",
        "gender": "M",
        "dob": "1972-04-28",
        "isLiving": true,
        "dod": null,
        "city": "Indore",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 80,
        "fullName": "Lata Vishwakarma",
        "gender": "F",
        "dob": "1978-01-01",
        "isLiving": true,
        "dod": null,
        "city": "Indore",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 81,
        "fullName": "Sankar Lal Vishwakarma",
        "gender": "M",
        "dob": "1956-01-01",
        "isLiving": true,
        "dod": null,
        "city": "Sekhukhera",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 82,
        "fullName": "Shanta Bai Vishwakarma",
        "gender": "F",
        "dob": "1965-01-01",
        "isLiving": true,
        "dod": null,
        "city": "Sekukhera",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 83,
        "fullName": "Shubham Vishwakarma",
        "gender": "M",
        "dob": "1996-03-23",
        "isLiving": true,
        "dod": null,
        "city": "Indore",
        "mobile": "7000646248",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 84,
        "fullName": "Shivani Vishwakarma",
        "gender": "F",
        "dob": "1999-04-01",
        "isLiving": true,
        "dod": null,
        "city": "Indore",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    },
    {
        "id": 85,
        "fullName": "Hitansh Vishwakarma",
        "gender": "M",
        "dob": "2022-09-20",
        "isLiving": true,
        "dod": null,
        "city": "Indore",
        "mobile": "",
        "gotra": "Khedavdiya",
        "state": "Madhya Pradesh"
    }
],
"familyTree_relations" : [
  {"relatesToMemberId":2,"relatedMemberId":1,"relationType":"Husband"},
  {"relatesToMemberId":1,"relatedMemberId":2,"relationType":"Wife"},
  {"relatesToMemberId":3,"relatedMemberId":1,"relationType":"Father"},
  {"relatesToMemberId":3,"relatedMemberId":2,"relationType":"Mother"},
  {"relatesToMemberId":4,"relatedMemberId":3,"relationType":"Husband"},
  {"relatesToMemberId":3,"relatedMemberId":4,"relationType":"Husband"},
  {"relatesToMemberId":5,"relatedMemberId":3,"relationType":"Father"},
  {"relatesToMemberId":5,"relatedMemberId":4,"relationType":"Mother"},
  {"relatesToMemberId":6,"relatedMemberId":5,"relationType":"Husband"},
  {"relatesToMemberId":5,"relatedMemberId":6,"relationType":"Wife"},
  {"relatesToMemberId":10,"relatedMemberId":1,"relationType":"Father"},
  {"relatesToMemberId":10,"relatedMemberId":2,"relationType":"Mother"},
  {"relatesToMemberId":11,"relatedMemberId":10,"relationType":"Wife"},
  {"relatesToMemberId":10,"relatedMemberId":11,"relationType":"Husband"},
  {"relatesToMemberId":10,"relatedMemberId":11,"relationType":"Wife"},
  {"relatesToMemberId":12,"relatedMemberId":11,"relationType":"Father"},
  {"relatesToMemberId":12,"relatedMemberId":10,"relationType":"Mother"},
  {"relatesToMemberId":14,"relatedMemberId":13,"relationType":"Husband"},
  {"relatesToMemberId":13,"relatedMemberId":14,"relationType":"Husband"},
  {"relatesToMemberId":11,"relatedMemberId":13,"relationType":"Father"},
  {"relatesToMemberId":11,"relatedMemberId":14,"relationType":"Mother"},
  {"relatesToMemberId":15,"relatedMemberId":12,"relationType":"Father"},
  {"relatesToMemberId":16,"relatedMemberId":12,"relationType":"Father"},
  {"relatesToMemberId":17,"relatedMemberId":1,"relationType":"Father"},
  {"relatesToMemberId":17,"relatedMemberId":2,"relationType":"Mother"},
  {"relatesToMemberId":18,"relatedMemberId":17,"relationType":"Husband"},
  {"relatesToMemberId":17,"relatedMemberId":18,"relationType":"Husband"},
  {"relatesToMemberId":19,"relatedMemberId":17,"relationType":"Father"},
  {"relatesToMemberId":19,"relatedMemberId":18,"relationType":"Mother"},
  {"relatesToMemberId":20,"relatedMemberId":19,"relationType":"Father"},
  {"relatesToMemberId":21,"relatedMemberId":19,"relationType":"Husband"},
  {"relatesToMemberId":19,"relatedMemberId":21,"relationType":"Husband"},
  {"relatesToMemberId":22,"relatedMemberId":12,"relationType":"Husband"},
  {"relatesToMemberId":12,"relatedMemberId":22,"relationType":"Husband"},
  {"relatesToMemberId":12,"relatedMemberId":22,"relationType":"Wife"},
  {"relatesToMemberId":22,"relatedMemberId":12,"relationType":"Wife"},
  {"relatesToMemberId":23,"relatedMemberId":7,"relationType":"Husband"},
  {"relatesToMemberId":7,"relatedMemberId":23,"relationType":"Husband"},
  {"relatesToMemberId":25,"relatedMemberId":24,"relationType":"Husband"},
  {"relatesToMemberId":24,"relatedMemberId":25,"relationType":"Husband"},
  {"relatesToMemberId":28,"relatedMemberId":27,"relationType":"Husband"},
  {"relatesToMemberId":27,"relatedMemberId":28,"relationType":"Husband"},
  {"relatesToMemberId":31,"relatedMemberId":30,"relationType":"Husband"},
  {"relatesToMemberId":30,"relatedMemberId":31,"relationType":"Husband"},
  {"relatesToMemberId":33,"relatedMemberId":17,"relationType":"Husband"},
  {"relatesToMemberId":17,"relatedMemberId":33,"relationType":"Husband"},
  {"relatesToMemberId":29,"relatedMemberId":33,"relationType":"Wife"},
  {"relatesToMemberId":33,"relatedMemberId":29,"relationType":"Husband"},
  {"relatesToMemberId":33,"relatedMemberId":29,"relationType":"Wife"},
  {"relatesToMemberId":34,"relatedMemberId":32,"relationType":"Husband"},
  {"relatesToMemberId":32,"relatedMemberId":34,"relationType":"Husband"},
  {"relatesToMemberId":35,"relatedMemberId":29,"relationType":"Father"},
  {"relatesToMemberId":35,"relatedMemberId":33,"relationType":"Mother"},
  {"relatesToMemberId":36,"relatedMemberId":35,"relationType":"Husband"},
  {"relatesToMemberId":35,"relatedMemberId":36,"relationType":"Husband"},
  {"relatesToMemberId":37,"relatedMemberId":35,"relationType":"Father"},
  {"relatesToMemberId":37,"relatedMemberId":36,"relationType":"Mother"},
  {"relatesToMemberId":38,"relatedMemberId":37,"relationType":"Husband"},
  {"relatesToMemberId":37,"relatedMemberId":38,"relationType":"Husband"},
  {"relatesToMemberId":39,"relatedMemberId":37,"relationType":"Father"},
  {"relatesToMemberId":39,"relatedMemberId":38,"relationType":"Mother"},
  {"relatesToMemberId":40,"relatedMemberId":37,"relationType":"Father"},
  {"relatesToMemberId":40,"relatedMemberId":38,"relationType":"Mother"},
  {"relatesToMemberId":41,"relatedMemberId":35,"relationType":"Father"},
  {"relatesToMemberId":41,"relatedMemberId":36,"relationType":"Mother"},
  {"relatesToMemberId":42,"relatedMemberId":41,"relationType":"Husband"},
  {"relatesToMemberId":41,"relatedMemberId":42,"relationType":"Husband"},
  {"relatesToMemberId":43,"relatedMemberId":41,"relationType":"Father"},
  {"relatesToMemberId":43,"relatedMemberId":42,"relationType":"Mother"},
  {"relatesToMemberId":44,"relatedMemberId":42,"relationType":"Mother"},
  {"relatesToMemberId":46,"relatedMemberId":45,"relationType":"Wife"},
  {"relatesToMemberId":45,"relatedMemberId":46,"relationType":"Husband"},
  {"relatesToMemberId":45,"relatedMemberId":46,"relationType":"Wife"},
  {"relatesToMemberId":47,"relatedMemberId":46,"relationType":"Father"},
  {"relatesToMemberId":47,"relatedMemberId":45,"relationType":"Mother"},
  {"relatesToMemberId":48,"relatedMemberId":32,"relationType":"Father"},
  {"relatesToMemberId":48,"relatedMemberId":34,"relationType":"Mother"},
  {"relatesToMemberId":49,"relatedMemberId":48,"relationType":"Husband"},
  {"relatesToMemberId":48,"relatedMemberId":49,"relationType":"Husband"},
  {"relatesToMemberId":50,"relatedMemberId":48,"relationType":"Father"},
  {"relatesToMemberId":50,"relatedMemberId":49,"relationType":"Mother"},
  {"relatesToMemberId":51,"relatedMemberId":50,"relationType":"Father"},
  {"relatesToMemberId":52,"relatedMemberId":48,"relationType":"Father"},
  {"relatesToMemberId":52,"relatedMemberId":49,"relationType":"Mother"},
  {"relatesToMemberId":53,"relatedMemberId":48,"relationType":"Father"},
  {"relatesToMemberId":53,"relatedMemberId":49,"relationType":"Mother"},
  {"relatesToMemberId":54,"relatedMemberId":32,"relationType":"Father"},
  {"relatesToMemberId":54,"relatedMemberId":34,"relationType":"Mother"},
  {"relatesToMemberId":55,"relatedMemberId":54,"relationType":"Husband"},
  {"relatesToMemberId":54,"relatedMemberId":55,"relationType":"Husband"},
  {"relatesToMemberId":57,"relatedMemberId":32,"relationType":"Father"},
  {"relatesToMemberId":57,"relatedMemberId":34,"relationType":"Mother"},
  {"relatesToMemberId":58,"relatedMemberId":27,"relationType":"Father"},
  {"relatesToMemberId":58,"relatedMemberId":28,"relationType":"Mother"},
  {"relatesToMemberId":59,"relatedMemberId":58,"relationType":"Husband"},
  {"relatesToMemberId":58,"relatedMemberId":59,"relationType":"Husband"},
  {"relatesToMemberId":61,"relatedMemberId":60,"relationType":"Wife"},
  {"relatesToMemberId":60,"relatedMemberId":61,"relationType":"Husband"},
  {"relatesToMemberId":60,"relatedMemberId":61,"relationType":"Wife"},
  {"relatesToMemberId":62,"relatedMemberId":61,"relationType":"Father"},
  {"relatesToMemberId":62,"relatedMemberId":60,"relationType":"Mother"},
  {"relatesToMemberId":63,"relatedMemberId":62,"relationType":"Father"},
  {"relatesToMemberId":64,"relatedMemberId":62,"relationType":"Father"},
  {"relatesToMemberId":65,"relatedMemberId":63,"relationType":"Father"},
  {"relatesToMemberId":67,"relatedMemberId":64,"relationType":"Husband"},
  {"relatesToMemberId":64,"relatedMemberId":67,"relationType":"Husband"},
  {"relatesToMemberId":68,"relatedMemberId":63,"relationType":"Husband"},
  {"relatesToMemberId":63,"relatedMemberId":68,"relationType":"Husband"},
  {"relatesToMemberId":69,"relatedMemberId":64,"relationType":"Father"},
  {"relatesToMemberId":69,"relatedMemberId":67,"relationType":"Mother"},
  {"relatesToMemberId":70,"relatedMemberId":64,"relationType":"Father"},
  {"relatesToMemberId":70,"relatedMemberId":67,"relationType":"Mother"},
  {"relatesToMemberId":71,"relatedMemberId":62,"relationType":"Husband"},
  {"relatesToMemberId":62,"relatedMemberId":71,"relationType":"Husband"},
  {"relatesToMemberId":72,"relatedMemberId":62,"relationType":"Father"},
  {"relatesToMemberId":72,"relatedMemberId":71,"relationType":"Mother"},
  {"relatesToMemberId":73,"relatedMemberId":72,"relationType":"Wife"},
  {"relatesToMemberId":72,"relatedMemberId":73,"relationType":"Husband"},
  {"relatesToMemberId":72,"relatedMemberId":73,"relationType":"Wife"},
  {"relatesToMemberId":74,"relatedMemberId":24,"relationType":"Father"},
  {"relatesToMemberId":74,"relatedMemberId":25,"relationType":"Mother"},
  {"relatesToMemberId":75,"relatedMemberId":74,"relationType":"Wife"},
  {"relatesToMemberId":74,"relatedMemberId":75,"relationType":"Husband"},
  {"relatesToMemberId":74,"relatedMemberId":75,"relationType":"Wife"},
  {"relatesToMemberId":76,"relatedMemberId":75,"relationType":"Father"},
  {"relatesToMemberId":76,"relatedMemberId":74,"relationType":"Mother"},
  {"relatesToMemberId":77,"relatedMemberId":75,"relationType":"Father"},
  {"relatesToMemberId":77,"relatedMemberId":74,"relationType":"Mother"},
  {"relatesToMemberId": 1, "relatedMemberId": 7, "relationType": "Father"},
  {"relatesToMemberId": 1, "relatedMemberId": 23, "relationType": "Mother"},
  {"relatesToMemberId": 7, "relatedMemberId": 24, "relationType": "Father"},
    {"relatesToMemberId": 7, "relatedMemberId": 25, "relationType": "Mother"},
    {"relatesToMemberId": 24, "relatedMemberId": 26, "relationType": "Father"},
    {"relatesToMemberId": 29, "relatedMemberId": 24, "relationType": "Father"},
    {"relatesToMemberId": 29, "relatedMemberId": 25, "relationType": "Mother"},
    {"relatesToMemberId": 30, "relatedMemberId": 24, "relationType": "Father"},
    {"relatesToMemberId": 30, "relatedMemberId": 25, "relationType": "Mother"},
    {"relatesToMemberId": 32, "relatedMemberId": 24, "relationType": "Father"},
    {"relatesToMemberId": 32, "relatedMemberId": 25, "relationType": "Mother"},
    {"relatesToMemberId": 78, "relatedMemberId": 5, "relationType": "Father"},
    {"relatesToMemberId": 78, "relatedMemberId": 6, "relationType": "Mother"},
    {"relatesToMemberId": 80, "relatedMemberId": 79, "relationType": "Husband"},
    {"relatesToMemberId": 79, "relatedMemberId": 80, "relationType": "Wife"},
    {"relatesToMemberId": 6, "relatedMemberId": 79, "relationType": "Father"},
    {"relatesToMemberId": 6, "relatedMemberId": 80, "relationType": "Mother"},
    {"relatesToMemberId": 9, "relatedMemberId": 5, "relationType": "Father"},
    {"relatesToMemberId": 9, "relatedMemberId": 6, "relationType": "Mother"},
    {"relatesToMemberId": 82, "relatedMemberId": 81, "relationType": "Husband"},
    {"relatesToMemberId": 81, "relatedMemberId": 82, "relationType": "Wife"},
    {"relatesToMemberId": 4, "relatedMemberId": 82, "relationType": "Mother"},
    {"relatesToMemberId": 4, "relatedMemberId": 81, "relationType": "Father"},
    {"relatesToMemberId": 83, "relatedMemberId": 79, "relationType": "Father"},
    {"relatesToMemberId": 83, "relatedMemberId": 80, "relationType": "Mother"},
    {"relatesToMemberId": 84, "relatedMemberId": 83, "relationType": "Husband"},
    {"relatesToMemberId": 83, "relatedMemberId": 84, "relationType": "Wife"},
    {"relatesToMemberId": 85, "relatedMemberId": 83, "relationType": "Father"},
    {"relatesToMemberId": 85, "relatedMemberId": 84, "relationType": "Mother"}
]
}
"""

object BackupUtils {

    /**
     * Parses the JSON backup string into lists of FamilyMember and FamilyRelation.
     * It handles the mapping of old keys (id, member1Id, member2Id) to new keys.
     */
    fun parseBackupData(backupData: String): Pair<List<FamilyMember>, List<FamilyRelation>> {
        val membersList = mutableListOf<FamilyMember>()
        val relationsList = mutableListOf<FamilyRelation>()

        try {
            val jsonObject = JSONObject(backupData)

            // --- Parse Members ---
            if (jsonObject.has("familyTree_members")) {
                val jsonArray = jsonObject.getJSONArray("familyTree_members")
                for (i in 0 until jsonArray.length()) {
                    val obj = jsonArray.getJSONObject(i)
                    membersList.add(
                        FamilyMember(
                            memberId = obj.getInt("id"), // Mapping 'id' to 'memberId'
                            fullName = obj.getString("fullName"),
                            gender = obj.getString("gender"),
                            dob = obj.getString("dob"),
                            isLiving = obj.getBoolean("isLiving"),
                            dod = if (obj.isNull("dod")) "" else obj.getString("dod"),
                            city = if (obj.isNull("city")) "" else obj.getString("city"),
                            gotra = if (obj.isNull("gotra")) "" else obj.getString("gotra"),
                            state = if (obj.isNull("state")) "" else obj.getString("state"),
                            mobile = if (obj.isNull("mobile")) "" else obj.getString("mobile")
                        )
                    )
                }
            }

            // --- Parse Relations ---
            if (jsonObject.has("familyTree_relations")) {
                val jsonArray = jsonObject.getJSONArray("familyTree_relations")
                for (i in 0 until jsonArray.length()) {
                    val obj = jsonArray.getJSONObject(i)
                    relationsList.add(
                        FamilyRelation(
                            relatesToMemberId = obj.getInt("relatesToMemberId"), // Mapping 'member1Id'
                            relatedMemberId = obj.getInt("relatedMemberId"), // Mapping 'member2Id'
                            relationType = obj.getString("relationType")
                        )
                    )
                }
            }
        } catch (e: Exception) {
            // Log the error during parsing
            println("Error parsing JSON backup data: ${e.message}")
        }


        return Pair(membersList, relationsList)
    }
}
