package com.pratik.learning.familyTree.utils



const val GENDER_TYPE_MALE = "M"
const val GENDER_TYPE_FEMALE = "F"
const val RELATION_TYPE_FATHER = "Father"
const val RELATION_TYPE_MOTHER = "Mother"
const val RELATION_TYPE_CHILD = "Child"
const val RELATION_TYPE_SIBLING = "Sibling"
const val RELATION_TYPE_SON = "Son"
const val RELATION_TYPE_DAUGHTER = "Daughter"
const val RELATION_TYPE_HUSBAND = "Husband"
const val RELATION_TYPE_WIFE = "Wife"
const val RELATION_TYPE_BROTHER = "Brother"
const val RELATION_TYPE_SISTER = "Sister"
const val RELATION_TYPE_SON_IN_LAW = "Son In Law"
const val RELATION_TYPE_DAUGHTER_IN_LAW = "Daughter In Law"
const val RELATION_TYPE_FATHER_IN_LAW = "Father In Law"
const val RELATION_TYPE_MOTHER_IN_LAW = "Mother In Law"
const val RELATION_TYPE_GRANDFATHER_F = "GrandFather"
const val RELATION_TYPE_GRANDMOTHER_F = "GrandMotherF"
const val RELATION_TYPE_GRANDFATHER_M = "GrandFatherM"
const val RELATION_TYPE_GRANDMOTHER_M = "GrandMotherM"
const val RELATION_TYPE_GRANDCHILD = "Grandchild"
const val RELATION_TYPE_GRANDCHILD_F = "Grandchild_F"
const val RELATION_TYPE_GREAT_GRANDCHILD = "Great Grandchild"
const val RELATION_TYPE_GREAT_GREAT_GRANDCHILD = "Great Great Grandchild"
const val RELATION_TYPE_GREAT____GRANDCHILD = "Great .... Great Grandchild"

const val DATA_BACKUP_FILE_NAME = "data_backup.json"
const val DATA_BACKUP_FILE_PATH = "dataBackUp/$DATA_BACKUP_FILE_NAME"
